blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/wigglep1ne/wigglep1ne.github.io/discussions/new?category=q-a
    about: Ask questions and discuss with other community members.
  - name: Feature request
    url: https://github.com/wigglep1ne/wigglep1ne.github.io/discussions/new?category=ideas
    about: Share ideas for new features.
